accesslog = "/var/log/hypercorn/access.log"
errorlog = "/var/log/hypercorn/errors.log"
loglevel = "DEBUG"
alt_svc_headers = ["h3=\":4433\"; ma=3600, h3-34=\":4433\"; ma=3600"]
bind = ["0.0.0.0:4433"]
quic_bind = ["0.0.0.0:4433"]
insecure_bind = ["0.0.0.0:8080"]
certfile = "/tmp/server.crt"
keyfile = "/tmp/server.key"
#server_names = ["pythonrestapi"]
worker_class = "asyncio"
workers = 100
